# Generated by Django 3.0.2 on 2020-02-13 05:59

import FakeNewsApp.models
import FakeNewsApp.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_auto_20200203_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default='201134175723', max_length=12, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('src', models.TextField()),
                ('articleType', models.CharField(choices=[('Sports', 'Sports'), ('Politics', 'Politics'), ('Regional', 'Regional'), ('International', 'International'), ('Crime', 'Crime'), ('Technology', 'Technology'), ('Other', 'Other')], default='Other', max_length=13)),
                ('img', models.FileField(blank=True, null=True, storage=FakeNewsApp.storage.OverwriteStorage(), upload_to=FakeNewsApp.models.Article.article_directory_path)),
                ('audit_requested', models.DateTimeField(blank=True, null=True)),
                ('audit_completed', models.DateTimeField(blank=True, null=True)),
                ('audit_status', models.BooleanField(default=False)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('block_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('dp', models.FileField(blank=True, null=True, storage=FakeNewsApp.storage.OverwriteStorage(), upload_to=FakeNewsApp.models.Auditor.user_directory_path_dp)),
                ('idproof', models.FileField(blank=True, null=True, storage=FakeNewsApp.storage.OverwriteStorage(), upload_to=FakeNewsApp.models.Auditor.user_directory_path_idproof)),
                ('verified', models.BooleanField(default=False)),
                ('verification_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('idproof', models.FileField(null=True, storage=FakeNewsApp.storage.OverwriteStorage(), upload_to=FakeNewsApp.models.Journalist.user_directory_path_idproof)),
                ('dp', models.FileField(null=True, storage=FakeNewsApp.storage.OverwriteStorage(), upload_to=FakeNewsApp.models.Journalist.user_directory_path_dp)),
                ('verified', models.BooleanField(default=False)),
                ('verification_time', models.DateTimeField(blank=True, null=True)),
                ('deactivation_time', models.DateTimeField(blank=True, null=True)),
                ('deactivations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('dp', models.FileField(null=True, storage=FakeNewsApp.storage.OverwriteStorage(), upload_to=FakeNewsApp.models.Reader.user_directory_path_dp)),
            ],
        ),
        migrations.CreateModel(
            name='StakeTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('tranType', models.CharField(choices=[('+', 'Add'), ('-', 'Remove')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FakeNewsApp.Auditor')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FakeNewsApp.Article')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FakeNewsApp.Reader')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FakeNewsApp.Article')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FakeNewsApp.Reader')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=10000)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FakeNewsApp.Article')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FakeNewsApp.Reader')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FakeNewsApp.Auditor'),
        ),
        migrations.AddField(
            model_name='article',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FakeNewsApp.Journalist'),
        ),
    ]
