# Generated by Django 3.0.2 on 2020-02-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default='366896810556', max_length=12, primary_key=True, serialize=False),
        ),
    ]
