# Generated by Django 3.0.2 on 2020-02-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0003_auto_20200213_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default='191990803544', max_length=12, primary_key=True, serialize=False),
        ),
    ]
