# Generated by Django 3.0.2 on 2020-02-13 06:01

import FakeNewsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0005_auto_20200213_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=FakeNewsApp.models.StringKeyGenerator, max_length=12, primary_key=True, serialize=False),
        ),
    ]
