# Generated by Django 3.0.2 on 2020-02-13 16:30

import FakeNewsApp.models
import FakeNewsApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0006_auto_20200213_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audit_completed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='dp',
            field=models.FileField(blank=True, null=True, storage=FakeNewsApp.storage.OverwriteStorage(), upload_to=FakeNewsApp.models.Journalist.user_directory_path_dp),
        ),
        migrations.AlterField(
            model_name='reader',
            name='dp',
            field=models.FileField(blank=True, null=True, storage=FakeNewsApp.storage.OverwriteStorage(), upload_to=FakeNewsApp.models.Reader.user_directory_path_dp),
        ),
    ]
