# Generated by Django 3.0.2 on 2020-02-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsApp', '0007_auto_20200213_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audit_completed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
